services:
  postgres:
    image: postgres:13
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: test_password
      POSTGRES_DB: foodlog_test
    ports:
      - "5432:5432"
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d foodlog_test"]
      interval: 10s
      timeout: 5s
      retries: 3

  app:
    build: .
    environment:
      - NODE_ENV=test
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_USERNAME=postgres
      - DB_PASSWORD=test_password
      - DB_NAME=foodlog_test
    depends_on:
      postgres:
        condition: service_healthy
    command: npm run test:ci